Proper upgarde to Humble with fixed typos & dependencies
AGH-CEAI/ros2_net_ft_driver pull request #3
Opened 2024-10-10 15:52 UTC by macmacal

## Description
**Fixes:**
- missing dependencies (`xarco`, `ros2_control`)
- corrected all typos from `ati_axia` to `ati_axia80` (probably this should be revisited...),
- corrected arguments to launch node `controller_manager` in the launch file (from now the `robot_description` must be given directly from the topic),
- introduced a simple assert in `net_ft_interface.hpp` to explain the _Segmentation Fault_ from attempting to retrieve a non-existent factory from the `std::map<std::string, NetFTFactory*>`,

**Changes:**
- introduced pre-commit hook to autoformat the XML (both `.xarco` and `package.xml`) files,
- derived the launch flag `use_physical_hardware` to the default launch file for testing convince,
- defined missing C++ standard as version 17 (in the `CMakeLists.txt`),

## Motivation and Context

This PR was created to fix all bugs regarding launching the package in the Humble distribution. 

## How Has This Been Tested?

Manually, launching the driver with the physical ATI AXIA80 ft sensor.

Used a docker container with RT capabilities:
```yaml
cap_add:
     - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
```

## Checklist:

- [ ] All TODOs in the code has been resolved or linked with a proper issue.
- [ ] Code is (auto)formatted.
- [ ] Documentation (README/CHANGELOG/Wiki/etc) has been updated.
- [ ] All automatic checks passed.

2024-10-10 16:12 UTC, macmacal commented on net_ft_driver/include/net_ft_driver/interfaces/net_ft_interface.hpp
> +      throw std::runtime_error("Sensor type not supported: " + sensor_type);
Consider to improve the verbosity of the output for the end user. Currently it looks like this:

![image](https://github.com/user-attachments/assets/1175f320-0afa-459d-946f-1bae6222dcb5)

2024-10-11 16:30 UTC, sivral requested changes

2024-10-11 16:30 UTC, sivral commented on README.md
>  ```Bash
Please be consistent with the markdown.

2024-10-11 16:45 UTC, macmacal commented on README.md
>  ```Bash
done

2024-10-11 16:49 UTC, macmacal commented on net_ft_driver/include/net_ft_driver/interfaces/net_ft_interface.hpp
> +      throw std::runtime_error("Sensor type not supported: " + sensor_type);
For now its just ~one liner, good enough to be in the `.hpp` file. Also, there is no obvious way to get the logger.

2024-10-11 16:50 UTC, sivral approved these changes

2024-10-11 16:59 UTC, macmacal reviewed
LGTM

2024-10-11 17:01 UTC, merged